' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace MySqlWindowsFormsApplication5
	
	Public Class frmambulance_service
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmambulance_service_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=localhost;user id=root;database=hospital;password=fus939597;persistsecurityinfo=True;allowuservariables=True;"
			ad = New MySqlDataAdapter("select * from `ambulance_service`", strConn)
			Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
			ad.Fill(Me.newDataSet.ambulance_service)
			ad.DeleteCommand = builder.GetDeleteCommand()
			ad.UpdateCommand = builder.GetUpdateCommand()
			ad.InsertCommand = builder.GetInsertCommand()
			Dim ad3 As MySqlDataAdapter
			ad3 = New MySqlDataAdapter("select * from `patient`", strConn)
			ad3.Fill(Me.newDataSet.patient)
			Me.Patient_ID_comboBox.DataSource = Me.newDataSet.patient
			Me.Patient_ID_comboBox.DisplayMember = "Patient_ID"
			Me.Patient_ID_comboBox.ValueMember = "Patient_ID"
			Me.Patient_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.ambulance_serviceBindingSource, "Patient_ID", True))
			ad3.Dispose()
			ad3 = New MySqlDataAdapter("select * from `driver`", strConn)
			ad3.Fill(Me.newDataSet.driver)
			Me.Driver_ID_comboBox.DataSource = Me.newDataSet.driver
			Me.Driver_ID_comboBox.DisplayMember = "Driver_ID"
			Me.Driver_ID_comboBox.ValueMember = "Driver_ID"
			Me.Driver_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.ambulance_serviceBindingSource, "Driver_ID", True))
			ad3.Dispose()
			ad3 = New MySqlDataAdapter("select * from `ambulance`", strConn)
			ad3.Fill(Me.newDataSet.ambulance)
			Me.Ambulance_ID_comboBox.DataSource = Me.newDataSet.ambulance
			Me.Ambulance_ID_comboBox.DisplayMember = "Ambulance_ID"
			Me.Ambulance_ID_comboBox.ValueMember = "Ambulance_ID"
			Me.Ambulance_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.ambulance_serviceBindingSource, "Ambulance_ID", True))
			ad3.Dispose()
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			ambulance_serviceBindingSource.EndEdit()
			ad.Update(Me.newDataSet.ambulance_service)
		End Sub
		
		Private Sub frmambulance_service_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
        Private Sub AS_IDTextBox_Validating(sender As Object, e As CancelEventArgs) Handles AS_IDTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(AS_IDTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(AS_IDTextBox, "The field AS_ID is required")
            End If
            Dim v As Integer
            Dim s As String = AS_IDTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(AS_IDTextBox, "The field AS_ID must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(AS_IDTextBox, "")
            End If
        End Sub
		
        Private Sub Patient_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Patient_ID_comboBox.Validating
            Dim i As Integer = Patient_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Patient_ID_comboBox, "Must select a Patient_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Patient_ID_comboBox, "")
            End If
        End Sub
        Private Sub Driver_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Driver_ID_comboBox.Validating
            Dim i As Integer = Driver_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Driver_ID_comboBox, "Must select a Driver_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Driver_ID_comboBox, "")
            End If
        End Sub
        Private Sub Ambulance_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Ambulance_ID_comboBox.Validating
            Dim i As Integer = Ambulance_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Ambulance_ID_comboBox, "Must select a Ambulance_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Ambulance_ID_comboBox, "")
            End If
        End Sub
		
        Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
            ambulance_serviceBindingSource.AddNew()
        End Sub
        Private Sub Cmdend_Click(sender As Object, e As EventArgs) Handles Cmdend.Click
            Dim response As String
            response = MsgBox("Do you want to close?", MsgBoxStyle.YesNoCancel) 'a message will be displayed and answer will be stored as string variable
            If response = vbYes Then 'use of selection programming structure
                Me.Close()
            End If
        End Sub

        Private Sub Cmdmain_Click(sender As Object, e As EventArgs) Handles Cmdmain.Click
            frmmainreceptionist.Show()
            Me.Hide()
        End Sub
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            ambulance_serviceBindingSource.MoveNext()
        End Sub

        Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
            ambulance_serviceBindingSource.MovePrevious()
        End Sub

        Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
            ambulance_serviceBindingSource.MoveFirst()
        End Sub

        Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
            ambulance_serviceBindingSource.MoveLast()
        End Sub

        Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
            ad.Update(Me.newDataSet.ambulance_service)
        End Sub

        Private Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
            ambulance_serviceBindingSource.AddNew()
        End Sub

        Private Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
            ambulance_serviceBindingSource.RemoveCurrent()
        End Sub
    End Class
	
End Namespace
