
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 
Namespace MySqlWindowsFormsApplication4

    Public Class frmMain


        Private Sub ListBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListBox1.SelectedIndexChanged
        End Sub

        Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
            TextBox2.Text = "" 'clears the password text box
        End Sub

        Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
            If TextBox2.Text = "R" And ListBox1.SelectedIndex = 0 Then 'use of selection programming structure
                frmmainreceptionist.Show() 'opens receptionist main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "D" And ListBox1.SelectedIndex = 1 Then 'use of selection programming structure
                frmmaindoctor.Show() 'opens doctor main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "N" And ListBox1.SelectedIndex = 2 Then 'use of selection programming structure
                frmmainnurse.Show() 'opens nurse main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "A" And ListBox1.SelectedIndex = 3 Then 'use of selection programming structure
                frmaccountantmain.Show() 'opens accountant main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "W" And ListBox1.SelectedIndex = 4 Then 'use of selection programming structure
                frmmainwardboy.Show() 'opens ward boy main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "C" And ListBox1.SelectedIndex = 5 Then 'use of selection programming structure
                frmmaincarrier.Show() 'opens carrier main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            ElseIf TextBox2.Text = "G" And ListBox1.SelectedIndex = 6 Then 'use of selection programming structure
                frmmainguest.Show() 'opens guest main menu when password is correct
                TextBox2.Text = ""
                Me.Hide()
            Else
                MsgBox("Invalid password, please try again.") 'error message on wrong password
            End If

        End Sub
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            Dim response As String
            response = MsgBox("Do you want to close?", MsgBoxStyle.YesNoCancel) 'a message will be displayed and answer will be stored as string variable
            If response = vbYes Then 'use of selection programming structure
                Me.Close()
            End If
        End Sub


        Private Sub PictureBox1_Click(sender As Object, e As EventArgs) Handles PictureBox1.Click

        End Sub

        Private Sub Label3_Click(sender As Object, e As EventArgs) Handles Label3.Click

        End Sub
    End Class

End Namespace
