' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace MySqlWindowsFormsApplication5
	
    Public Class frmnursing_servicenurse

        Private ad As MySqlDataAdapter

        Private Sub frmnursing_service_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=localhost;user id=root;database=hospital;password=fus939597;persistsecurityinfo=True;allowuservariables=True;"
            ad = New MySqlDataAdapter("select * from `nursing_service`", strConn)
            Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
            ad.Fill(Me.newDataSet.nursing_service)
            ad.DeleteCommand = builder.GetDeleteCommand()
            ad.UpdateCommand = builder.GetUpdateCommand()
            ad.InsertCommand = builder.GetInsertCommand()
            Dim ad3 As MySqlDataAdapter
            ad3 = New MySqlDataAdapter("select * from `nurse`", strConn)
            ad3.Fill(Me.newDataSet.nurse)
            Me.Nurse_ID_comboBox.DataSource = Me.newDataSet.nurse
            Me.Nurse_ID_comboBox.DisplayMember = "Nurse_ID"
            Me.Nurse_ID_comboBox.ValueMember = "Nurse_ID"
            Me.Nurse_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.NursingserviceBindingSource, "Nurse_ID", True))
            ad3.Dispose()
            ad3 = New MySqlDataAdapter("select * from `patient`", strConn)
            ad3.Fill(Me.newDataSet.patient)
            Me.Patient_ID_comboBox.DataSource = Me.newDataSet.patient
            Me.Patient_ID_comboBox.DisplayMember = "Patient_ID"
            Me.Patient_ID_comboBox.ValueMember = "Patient_ID"
            Me.Patient_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.NursingserviceBindingSource, "Patient_ID", True))
            ad3.Dispose()
            ad3 = New MySqlDataAdapter("select * from `room`", strConn)
            ad3.Fill(Me.newDataSet.room)
            Me.Room_ID_comboBox.DataSource = Me.newDataSet.room
            Me.Room_ID_comboBox.DisplayMember = "Room_ID"
            Me.Room_ID_comboBox.ValueMember = "Room_ID"
            Me.Room_ID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.NursingserviceBindingSource, "Room_ID", True))
            ad3.Dispose()
        End Sub


        Private Sub frmnursing_service_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
            e.Cancel = False
        End Sub

        Private Sub NS_IDTextBox_Validating(sender As Object, e As CancelEventArgs) Handles NS_IDTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(NS_IDTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(NS_IDTextBox, "The field NS_ID is required")
            End If
            Dim v As Integer
            Dim s As String = NS_IDTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(NS_IDTextBox, "The field NS_ID must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(NS_IDTextBox, "")
            End If
        End Sub

        Private Sub Nurse_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Nurse_ID_comboBox.Validating
            Dim i As Integer = Nurse_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Nurse_ID_comboBox, "Must select a Nurse_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Nurse_ID_comboBox, "")
            End If
        End Sub
        Private Sub Patient_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Patient_ID_comboBox.Validating
            Dim i As Integer = Patient_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Patient_ID_comboBox, "Must select a Patient_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Patient_ID_comboBox, "")
            End If
        End Sub
        Private Sub Room_ID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles Room_ID_comboBox.Validating
            Dim i As Integer = Room_ID_comboBox.SelectedIndex
            e.Cancel = False
            If i = -1 Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_ID_comboBox, "Must select a Room_ID")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Room_ID_comboBox, "")
            End If
        End Sub

        Private Sub Cmdmain_Click(sender As Object, e As EventArgs) Handles Cmdmain.Click
            frmmainnurse.Show()
            Me.Hide()
        End Sub
        Private Sub Cmdend_Click(sender As Object, e As EventArgs) Handles Cmdend.Click
            Dim response As String
            response = MsgBox("Do you want to close?", MsgBoxStyle.YesNoCancel) 'a message will be displayed and answer will be stored as string variable
            If response = vbYes Then 'use of selection programming structure
                Me.Close()
            End If
        End Sub
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            NursingserviceBindingSource.MoveNext()
        End Sub

        Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
            NursingserviceBindingSource.MovePrevious()
        End Sub

        Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
            NursingserviceBindingSource.MoveFirst()
        End Sub

        Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
            NursingserviceBindingSource.MoveLast()
        End Sub

        Private Sub Button5_Click(sender As Object, e As EventArgs)
            ad.Update(Me.newDataSet.nursing_service)
        End Sub

        Private Sub Button6_Click(sender As Object, e As EventArgs)
            NursingserviceBindingSource.AddNew()
        End Sub

        Private Sub Button7_Click(sender As Object, e As EventArgs)
            NursingserviceBindingSource.RemoveCurrent()
        End Sub

        Private Sub ToolStripButton2_Click(sender As Object, e As EventArgs) Handles ToolStripButton2.Click
            Try
                Me.Nursing_serviceTableAdapter.Fill(Me.HospitalDataSet.nursing_service, CType(ToolStripTextBox1.Text, Integer))
                Me.Patient1TableAdapter.Fill(Me.HospitalDataSet.patient1, CType(ToolStripTextBox1.Text, Integer))
                Me.RoomTableAdapter.Fill(Me.HospitalDataSet.room, CType(ToolStripTextBox1.Text, Integer))
            Catch ex As System.Exception
                System.Windows.Forms.MessageBox.Show(ex.Message)
            End Try
        End Sub
    End Class
	
End Namespace
