' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace MySqlWindowsFormsApplication5
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmnursing_service
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmnursing_service))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.nursing_serviceBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.newDataSet = New NewDataSet()
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.DataGridView3 = New System.Windows.Forms.DataGridView()
            Me.RoomIDDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.RoomnumDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.RoomTypeDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.RoomCostDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.RoomBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.DataGridView2 = New System.Windows.Forms.DataGridView()
            Me.DataGridViewTextBoxColumn3 = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.DataGridViewTextBoxColumn4 = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.PatientBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.DataGridView1 = New System.Windows.Forms.DataGridView()
            Me.NurseIDDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.NurseNameDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.AgeDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.AddressDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.WorkShiftDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.ExperienceDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.SalaryDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.NurseBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.Button7 = New System.Windows.Forms.Button()
            Me.Label1 = New System.Windows.Forms.Label()
            Me.Button6 = New System.Windows.Forms.Button()
            Me.Cmdmain = New System.Windows.Forms.Button()
            Me.Button5 = New System.Windows.Forms.Button()
            Me.Button4 = New System.Windows.Forms.Button()
            Me.Cmdend = New System.Windows.Forms.Button()
            Me.Button3 = New System.Windows.Forms.Button()
            Me.CmdHelp = New System.Windows.Forms.Button()
            Me.Button2 = New System.Windows.Forms.Button()
            Me.NS_IDLabel = New System.Windows.Forms.Label()
            Me.Button1 = New System.Windows.Forms.Button()
            Me.NS_IDTextBox = New System.Windows.Forms.TextBox()
            Me.Nurse_IDLabel = New System.Windows.Forms.Label()
            Me.Nurse_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.Patient_IDLabel = New System.Windows.Forms.Label()
            Me.Patient_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.Room_IDLabel = New System.Windows.Forms.Label()
            Me.Room_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.nursing_serviceBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            CType(Me.DataGridView3, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.RoomBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.DataGridView2, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.PatientBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.DataGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.NurseBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.panel3.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.nursing_serviceBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(10, 0, 10, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(1057, 25)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'nursing_serviceBindingSource
            '
            Me.nursing_serviceBindingSource.DataMember = "nursing_service"
            Me.nursing_serviceBindingSource.DataSource = Me.newDataSet
            '
            'newDataSet
            '
            Me.newDataSet.DataSetName = "NewDataSet"
            Me.newDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(35, 22)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(50, 23)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(23, 22)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.BackgroundImage = Global.MySqlWindowsFormsApplication5.My.Resources.Resources._6800415_light_blue_backgrounds
            Me.Panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
            Me.Panel1.Controls.Add(Me.DataGridView3)
            Me.Panel1.Controls.Add(Me.DataGridView2)
            Me.Panel1.Controls.Add(Me.DataGridView1)
            Me.Panel1.Controls.Add(Me.Button7)
            Me.Panel1.Controls.Add(Me.Label1)
            Me.Panel1.Controls.Add(Me.Button6)
            Me.Panel1.Controls.Add(Me.Cmdmain)
            Me.Panel1.Controls.Add(Me.Button5)
            Me.Panel1.Controls.Add(Me.Button4)
            Me.Panel1.Controls.Add(Me.Cmdend)
            Me.Panel1.Controls.Add(Me.Button3)
            Me.Panel1.Controls.Add(Me.CmdHelp)
            Me.Panel1.Controls.Add(Me.Button2)
            Me.Panel1.Controls.Add(Me.NS_IDLabel)
            Me.Panel1.Controls.Add(Me.Button1)
            Me.Panel1.Controls.Add(Me.NS_IDTextBox)
            Me.Panel1.Controls.Add(Me.Nurse_IDLabel)
            Me.Panel1.Controls.Add(Me.Nurse_ID_comboBox)
            Me.Panel1.Controls.Add(Me.Patient_IDLabel)
            Me.Panel1.Controls.Add(Me.Patient_ID_comboBox)
            Me.Panel1.Controls.Add(Me.Room_IDLabel)
            Me.Panel1.Controls.Add(Me.Room_ID_comboBox)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.Location = New System.Drawing.Point(10, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(10, 3, 10, 3)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(1037, 688)
            Me.Panel1.TabIndex = 1
            '
            'DataGridView3
            '
            Me.DataGridView3.AllowUserToAddRows = False
            Me.DataGridView3.AllowUserToDeleteRows = False
            Me.DataGridView3.AllowUserToOrderColumns = True
            Me.DataGridView3.AutoGenerateColumns = False
            Me.DataGridView3.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Me.DataGridView3.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.RoomIDDataGridViewTextBoxColumn, Me.RoomnumDataGridViewTextBoxColumn, Me.RoomTypeDataGridViewTextBoxColumn, Me.RoomCostDataGridViewTextBoxColumn})
            Me.DataGridView3.DataSource = Me.RoomBindingSource
            Me.DataGridView3.Location = New System.Drawing.Point(238, 424)
            Me.DataGridView3.Name = "DataGridView3"
            Me.DataGridView3.ReadOnly = True
            Me.DataGridView3.Size = New System.Drawing.Size(716, 93)
            Me.DataGridView3.TabIndex = 96
            '
            'RoomIDDataGridViewTextBoxColumn
            '
            Me.RoomIDDataGridViewTextBoxColumn.DataPropertyName = "Room_ID"
            Me.RoomIDDataGridViewTextBoxColumn.HeaderText = "Room_ID"
            Me.RoomIDDataGridViewTextBoxColumn.Name = "RoomIDDataGridViewTextBoxColumn"
            Me.RoomIDDataGridViewTextBoxColumn.ReadOnly = True
            '
            'RoomnumDataGridViewTextBoxColumn
            '
            Me.RoomnumDataGridViewTextBoxColumn.DataPropertyName = "Room_num"
            Me.RoomnumDataGridViewTextBoxColumn.HeaderText = "Room_num"
            Me.RoomnumDataGridViewTextBoxColumn.Name = "RoomnumDataGridViewTextBoxColumn"
            Me.RoomnumDataGridViewTextBoxColumn.ReadOnly = True
            '
            'RoomTypeDataGridViewTextBoxColumn
            '
            Me.RoomTypeDataGridViewTextBoxColumn.DataPropertyName = "Room_Type"
            Me.RoomTypeDataGridViewTextBoxColumn.HeaderText = "Room_Type"
            Me.RoomTypeDataGridViewTextBoxColumn.Name = "RoomTypeDataGridViewTextBoxColumn"
            Me.RoomTypeDataGridViewTextBoxColumn.ReadOnly = True
            '
            'RoomCostDataGridViewTextBoxColumn
            '
            Me.RoomCostDataGridViewTextBoxColumn.DataPropertyName = "Room_Cost"
            Me.RoomCostDataGridViewTextBoxColumn.HeaderText = "Room_Cost"
            Me.RoomCostDataGridViewTextBoxColumn.Name = "RoomCostDataGridViewTextBoxColumn"
            Me.RoomCostDataGridViewTextBoxColumn.ReadOnly = True
            '
            'RoomBindingSource
            '
            Me.RoomBindingSource.DataMember = "room"
            Me.RoomBindingSource.DataSource = Me.newDataSet
            '
            'DataGridView2
            '
            Me.DataGridView2.AllowUserToAddRows = False
            Me.DataGridView2.AllowUserToDeleteRows = False
            Me.DataGridView2.AllowUserToOrderColumns = True
            Me.DataGridView2.AutoGenerateColumns = False
            Me.DataGridView2.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Me.DataGridView2.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.DataGridViewTextBoxColumn3, Me.DataGridViewTextBoxColumn4})
            Me.DataGridView2.DataSource = Me.PatientBindingSource
            Me.DataGridView2.Location = New System.Drawing.Point(238, 325)
            Me.DataGridView2.Name = "DataGridView2"
            Me.DataGridView2.ReadOnly = True
            Me.DataGridView2.Size = New System.Drawing.Size(716, 93)
            Me.DataGridView2.TabIndex = 95
            '
            'DataGridViewTextBoxColumn3
            '
            Me.DataGridViewTextBoxColumn3.DataPropertyName = "Age"
            Me.DataGridViewTextBoxColumn3.HeaderText = "Age"
            Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
            Me.DataGridViewTextBoxColumn3.ReadOnly = True
            '
            'DataGridViewTextBoxColumn4
            '
            Me.DataGridViewTextBoxColumn4.DataPropertyName = "Address"
            Me.DataGridViewTextBoxColumn4.HeaderText = "Address"
            Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
            Me.DataGridViewTextBoxColumn4.ReadOnly = True
            '
            'PatientBindingSource
            '
            Me.PatientBindingSource.DataMember = "patient"
            Me.PatientBindingSource.DataSource = Me.newDataSet
            '
            'DataGridView1
            '
            Me.DataGridView1.AllowUserToAddRows = False
            Me.DataGridView1.AllowUserToDeleteRows = False
            Me.DataGridView1.AllowUserToOrderColumns = True
            Me.DataGridView1.AutoGenerateColumns = False
            Me.DataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Me.DataGridView1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.NurseIDDataGridViewTextBoxColumn, Me.NurseNameDataGridViewTextBoxColumn, Me.AgeDataGridViewTextBoxColumn, Me.AddressDataGridViewTextBoxColumn, Me.WorkShiftDataGridViewTextBoxColumn, Me.ExperienceDataGridViewTextBoxColumn, Me.SalaryDataGridViewTextBoxColumn})
            Me.DataGridView1.DataSource = Me.NurseBindingSource
            Me.DataGridView1.Location = New System.Drawing.Point(238, 226)
            Me.DataGridView1.Name = "DataGridView1"
            Me.DataGridView1.ReadOnly = True
            Me.DataGridView1.Size = New System.Drawing.Size(716, 93)
            Me.DataGridView1.TabIndex = 94
            '
            'NurseIDDataGridViewTextBoxColumn
            '
            Me.NurseIDDataGridViewTextBoxColumn.DataPropertyName = "Nurse_ID"
            Me.NurseIDDataGridViewTextBoxColumn.HeaderText = "Nurse_ID"
            Me.NurseIDDataGridViewTextBoxColumn.Name = "NurseIDDataGridViewTextBoxColumn"
            Me.NurseIDDataGridViewTextBoxColumn.ReadOnly = True
            '
            'NurseNameDataGridViewTextBoxColumn
            '
            Me.NurseNameDataGridViewTextBoxColumn.DataPropertyName = "Nurse_Name"
            Me.NurseNameDataGridViewTextBoxColumn.HeaderText = "Nurse_Name"
            Me.NurseNameDataGridViewTextBoxColumn.Name = "NurseNameDataGridViewTextBoxColumn"
            Me.NurseNameDataGridViewTextBoxColumn.ReadOnly = True
            '
            'AgeDataGridViewTextBoxColumn
            '
            Me.AgeDataGridViewTextBoxColumn.DataPropertyName = "Age"
            Me.AgeDataGridViewTextBoxColumn.HeaderText = "Age"
            Me.AgeDataGridViewTextBoxColumn.Name = "AgeDataGridViewTextBoxColumn"
            Me.AgeDataGridViewTextBoxColumn.ReadOnly = True
            '
            'AddressDataGridViewTextBoxColumn
            '
            Me.AddressDataGridViewTextBoxColumn.DataPropertyName = "Address"
            Me.AddressDataGridViewTextBoxColumn.HeaderText = "Address"
            Me.AddressDataGridViewTextBoxColumn.Name = "AddressDataGridViewTextBoxColumn"
            Me.AddressDataGridViewTextBoxColumn.ReadOnly = True
            '
            'WorkShiftDataGridViewTextBoxColumn
            '
            Me.WorkShiftDataGridViewTextBoxColumn.DataPropertyName = "WorkShift"
            Me.WorkShiftDataGridViewTextBoxColumn.HeaderText = "WorkShift"
            Me.WorkShiftDataGridViewTextBoxColumn.Name = "WorkShiftDataGridViewTextBoxColumn"
            Me.WorkShiftDataGridViewTextBoxColumn.ReadOnly = True
            '
            'ExperienceDataGridViewTextBoxColumn
            '
            Me.ExperienceDataGridViewTextBoxColumn.DataPropertyName = "Experience"
            Me.ExperienceDataGridViewTextBoxColumn.HeaderText = "Experience"
            Me.ExperienceDataGridViewTextBoxColumn.Name = "ExperienceDataGridViewTextBoxColumn"
            Me.ExperienceDataGridViewTextBoxColumn.ReadOnly = True
            '
            'SalaryDataGridViewTextBoxColumn
            '
            Me.SalaryDataGridViewTextBoxColumn.DataPropertyName = "salary"
            Me.SalaryDataGridViewTextBoxColumn.HeaderText = "salary"
            Me.SalaryDataGridViewTextBoxColumn.Name = "SalaryDataGridViewTextBoxColumn"
            Me.SalaryDataGridViewTextBoxColumn.ReadOnly = True
            '
            'NurseBindingSource
            '
            Me.NurseBindingSource.DataMember = "nurse"
            Me.NurseBindingSource.DataSource = Me.newDataSet
            '
            'Button7
            '
            Me.Button7.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button7.FlatAppearance.BorderSize = 4
            Me.Button7.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button7.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button7.Location = New System.Drawing.Point(767, 547)
            Me.Button7.Name = "Button7"
            Me.Button7.Size = New System.Drawing.Size(61, 40)
            Me.Button7.TabIndex = 92
            Me.Button7.Text = "Delete"
            Me.Button7.UseVisualStyleBackColor = True
            '
            'Label1
            '
            Me.Label1.AutoSize = True
            Me.Label1.BackColor = System.Drawing.Color.Transparent
            Me.Label1.Font = New System.Drawing.Font("Modern No. 20", 30.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Label1.Location = New System.Drawing.Point(425, 12)
            Me.Label1.Name = "Label1"
            Me.Label1.Size = New System.Drawing.Size(303, 41)
            Me.Label1.TabIndex = 51
            Me.Label1.Text = "Nursing Services"
            '
            'Button6
            '
            Me.Button6.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button6.FlatAppearance.BorderSize = 4
            Me.Button6.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button6.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button6.Location = New System.Drawing.Point(365, 547)
            Me.Button6.Name = "Button6"
            Me.Button6.Size = New System.Drawing.Size(61, 40)
            Me.Button6.TabIndex = 91
            Me.Button6.Text = "Addnew"
            Me.Button6.UseVisualStyleBackColor = True
            '
            'Cmdmain
            '
            Me.Cmdmain.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Cmdmain.FlatAppearance.BorderSize = 4
            Me.Cmdmain.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Cmdmain.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Cmdmain.Location = New System.Drawing.Point(544, 599)
            Me.Cmdmain.Name = "Cmdmain"
            Me.Cmdmain.Size = New System.Drawing.Size(88, 33)
            Me.Cmdmain.TabIndex = 50
            Me.Cmdmain.Text = "Return to Main"
            Me.Cmdmain.UseVisualStyleBackColor = True
            '
            'Button5
            '
            Me.Button5.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button5.FlatAppearance.BorderSize = 4
            Me.Button5.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button5.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button5.Location = New System.Drawing.Point(700, 547)
            Me.Button5.Name = "Button5"
            Me.Button5.Size = New System.Drawing.Size(61, 40)
            Me.Button5.TabIndex = 90
            Me.Button5.Text = "Save"
            Me.Button5.UseVisualStyleBackColor = True
            '
            'Button4
            '
            Me.Button4.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button4.FlatAppearance.BorderSize = 4
            Me.Button4.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button4.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button4.Location = New System.Drawing.Point(633, 547)
            Me.Button4.Name = "Button4"
            Me.Button4.Size = New System.Drawing.Size(61, 40)
            Me.Button4.TabIndex = 89
            Me.Button4.Text = "Last"
            Me.Button4.UseVisualStyleBackColor = True
            '
            'Cmdend
            '
            Me.Cmdend.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Cmdend.FlatAppearance.BorderSize = 4
            Me.Cmdend.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Cmdend.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Cmdend.Location = New System.Drawing.Point(638, 599)
            Me.Cmdend.Name = "Cmdend"
            Me.Cmdend.Size = New System.Drawing.Size(61, 33)
            Me.Cmdend.TabIndex = 49
            Me.Cmdend.Text = "Exit"
            Me.Cmdend.UseVisualStyleBackColor = True
            '
            'Button3
            '
            Me.Button3.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button3.FlatAppearance.BorderSize = 4
            Me.Button3.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button3.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button3.Location = New System.Drawing.Point(432, 547)
            Me.Button3.Name = "Button3"
            Me.Button3.Size = New System.Drawing.Size(61, 40)
            Me.Button3.TabIndex = 88
            Me.Button3.Text = "First"
            Me.Button3.UseVisualStyleBackColor = True
            '
            'CmdHelp
            '
            Me.CmdHelp.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.CmdHelp.FlatAppearance.BorderSize = 4
            Me.CmdHelp.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.CmdHelp.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.CmdHelp.Location = New System.Drawing.Point(501, 599)
            Me.CmdHelp.Name = "CmdHelp"
            Me.CmdHelp.Size = New System.Drawing.Size(37, 33)
            Me.CmdHelp.TabIndex = 48
            Me.CmdHelp.Text = "Help"
            Me.CmdHelp.UseVisualStyleBackColor = True
            '
            'Button2
            '
            Me.Button2.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button2.FlatAppearance.BorderSize = 4
            Me.Button2.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button2.Location = New System.Drawing.Point(499, 547)
            Me.Button2.Name = "Button2"
            Me.Button2.Size = New System.Drawing.Size(61, 40)
            Me.Button2.TabIndex = 87
            Me.Button2.Text = "Previous"
            Me.Button2.UseVisualStyleBackColor = True
            '
            'NS_IDLabel
            '
            Me.NS_IDLabel.AutoSize = True
            Me.NS_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.NS_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.NS_IDLabel.Location = New System.Drawing.Point(438, 76)
            Me.NS_IDLabel.Name = "NS_IDLabel"
            Me.NS_IDLabel.Size = New System.Drawing.Size(57, 20)
            Me.NS_IDLabel.TabIndex = 1
            Me.NS_IDLabel.Text = "NS_ID"
            '
            'Button1
            '
            Me.Button1.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button1.FlatAppearance.BorderSize = 4
            Me.Button1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button1.Location = New System.Drawing.Point(566, 547)
            Me.Button1.Name = "Button1"
            Me.Button1.Size = New System.Drawing.Size(61, 40)
            Me.Button1.TabIndex = 86
            Me.Button1.Text = "Next"
            Me.Button1.UseVisualStyleBackColor = True
            '
            'NS_IDTextBox
            '
            Me.NS_IDTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.nursing_serviceBindingSource, "NS_ID", True))
            Me.NS_IDTextBox.Location = New System.Drawing.Point(501, 76)
            Me.NS_IDTextBox.Name = "NS_IDTextBox"
            Me.NS_IDTextBox.Size = New System.Drawing.Size(206, 20)
            Me.NS_IDTextBox.TabIndex = 2
            '
            'Nurse_IDLabel
            '
            Me.Nurse_IDLabel.AutoSize = True
            Me.Nurse_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Nurse_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Nurse_IDLabel.Location = New System.Drawing.Point(418, 103)
            Me.Nurse_IDLabel.Name = "Nurse_IDLabel"
            Me.Nurse_IDLabel.Size = New System.Drawing.Size(77, 20)
            Me.Nurse_IDLabel.TabIndex = 3
            Me.Nurse_IDLabel.Text = "Nurse_ID"
            '
            'Nurse_ID_comboBox
            '
            Me.Nurse_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Nurse_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Nurse_ID_comboBox.FormattingEnabled = True
            Me.Nurse_ID_comboBox.Location = New System.Drawing.Point(501, 102)
            Me.Nurse_ID_comboBox.Name = "Nurse_ID_comboBox"
            Me.Nurse_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Nurse_ID_comboBox.TabIndex = 4
            '
            'Patient_IDLabel
            '
            Me.Patient_IDLabel.AutoSize = True
            Me.Patient_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Patient_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Patient_IDLabel.Location = New System.Drawing.Point(410, 130)
            Me.Patient_IDLabel.Name = "Patient_IDLabel"
            Me.Patient_IDLabel.Size = New System.Drawing.Size(85, 20)
            Me.Patient_IDLabel.TabIndex = 5
            Me.Patient_IDLabel.Text = "Patient_ID"
            '
            'Patient_ID_comboBox
            '
            Me.Patient_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Patient_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Patient_ID_comboBox.FormattingEnabled = True
            Me.Patient_ID_comboBox.Location = New System.Drawing.Point(501, 129)
            Me.Patient_ID_comboBox.Name = "Patient_ID_comboBox"
            Me.Patient_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Patient_ID_comboBox.TabIndex = 6
            '
            'Room_IDLabel
            '
            Me.Room_IDLabel.AutoSize = True
            Me.Room_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Room_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Room_IDLabel.Location = New System.Drawing.Point(417, 156)
            Me.Room_IDLabel.Name = "Room_IDLabel"
            Me.Room_IDLabel.Size = New System.Drawing.Size(78, 20)
            Me.Room_IDLabel.TabIndex = 7
            Me.Room_IDLabel.Text = "Room_ID"
            '
            'Room_ID_comboBox
            '
            Me.Room_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Room_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Room_ID_comboBox.FormattingEnabled = True
            Me.Room_ID_comboBox.Location = New System.Drawing.Point(501, 155)
            Me.Room_ID_comboBox.Name = "Room_ID_comboBox"
            Me.Room_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Room_ID_comboBox.TabIndex = 8
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 25)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(1057, 698)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(1047, 0)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(10, 688)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(10, 688)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 688)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(1057, 10)
            Me.panel6.TabIndex = 6
            '
            'frmnursing_service
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(1057, 723)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.Name = "frmnursing_service"
            Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
            Me.Text = "Nursing_Service"
            Me.WindowState = System.Windows.Forms.FormWindowState.Maximized
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.nursing_serviceBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            CType(Me.DataGridView3, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.RoomBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.DataGridView2, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.PatientBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.DataGridView1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.NurseBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
		Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents newDataSet As NewDataSet
		Friend WithEvents nursing_serviceBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents NS_IDTextBox As System.Windows.Forms.TextBox
		Friend WithEvents NS_IDLabel As System.Windows.Forms.Label
		Friend WithEvents Nurse_ID_comboBox As System.Windows.Forms.ComboBox
		Friend WithEvents Nurse_IDLabel As System.Windows.Forms.Label
		Friend WithEvents Patient_ID_comboBox As System.Windows.Forms.ComboBox
		Friend WithEvents Patient_IDLabel As System.Windows.Forms.Label
		Friend WithEvents Room_ID_comboBox As System.Windows.Forms.ComboBox
		Friend WithEvents Room_IDLabel As System.Windows.Forms.Label
		Friend WithEvents panel3 As System.Windows.Forms.Panel
		Friend WithEvents panel4 As System.Windows.Forms.Panel
		Friend WithEvents panel5 As System.Windows.Forms.Panel
        Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents Cmdmain As System.Windows.Forms.Button
        Friend WithEvents Cmdend As System.Windows.Forms.Button
        Friend WithEvents CmdHelp As System.Windows.Forms.Button
        Friend WithEvents Label1 As System.Windows.Forms.Label
        Friend WithEvents Button7 As System.Windows.Forms.Button
        Friend WithEvents Button6 As System.Windows.Forms.Button
        Friend WithEvents Button5 As System.Windows.Forms.Button
        Friend WithEvents Button4 As System.Windows.Forms.Button
        Friend WithEvents Button3 As System.Windows.Forms.Button
        Friend WithEvents Button2 As System.Windows.Forms.Button
        Friend WithEvents Button1 As System.Windows.Forms.Button
        Friend WithEvents DataGridView3 As System.Windows.Forms.DataGridView
        Friend WithEvents RoomIDDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents RoomnumDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents RoomTypeDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents RoomCostDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents RoomBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents DataGridView2 As System.Windows.Forms.DataGridView
        Friend WithEvents DataGridViewTextBoxColumn3 As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents DataGridViewTextBoxColumn4 As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents PatientBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents DataGridView1 As System.Windows.Forms.DataGridView
        Friend WithEvents NurseIDDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents NurseNameDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents AgeDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents AddressDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents WorkShiftDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents ExperienceDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents SalaryDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents NurseBindingSource As System.Windows.Forms.BindingSource
		
	End Class
	
End Namespace
