' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace MySqlWindowsFormsApplication5
	
    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
    Partial Class frmpaymentacc
        Inherits System.Windows.Forms.Form

        'Form overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()> _
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.  
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()> _
        Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmpaymentacc))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.paymentBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.newDataSet = New NewDataSet()
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.DataGridView3 = New System.Windows.Forms.DataGridView()
            Me.BillIDDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.BillPurposeDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.BillTotalDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.BillBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.DataGridView1 = New System.Windows.Forms.DataGridView()
            Me.PatientIDDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.PatientNameDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.AgeDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.GenderDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.AddressDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.DOBDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.MobnumDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.DichargedDataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
            Me.PatientBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.Button7 = New System.Windows.Forms.Button()
            Me.Label1 = New System.Windows.Forms.Label()
            Me.Button6 = New System.Windows.Forms.Button()
            Me.Cmdmain = New System.Windows.Forms.Button()
            Me.Button5 = New System.Windows.Forms.Button()
            Me.Button4 = New System.Windows.Forms.Button()
            Me.Cmdend = New System.Windows.Forms.Button()
            Me.Button3 = New System.Windows.Forms.Button()
            Me.CmdHelp = New System.Windows.Forms.Button()
            Me.Button2 = New System.Windows.Forms.Button()
            Me.Pay_IDLabel = New System.Windows.Forms.Label()
            Me.Button1 = New System.Windows.Forms.Button()
            Me.Pay_IDTextBox = New System.Windows.Forms.TextBox()
            Me.Accnt_IDLabel = New System.Windows.Forms.Label()
            Me.Accnt_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.Bill_IDLabel = New System.Windows.Forms.Label()
            Me.Bill_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.Patient_IDLabel = New System.Windows.Forms.Label()
            Me.Patient_ID_comboBox = New System.Windows.Forms.ComboBox()
            Me.Pay_DateLabel = New System.Windows.Forms.Label()
            Me.Pay_Date_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.Pay_TimeLabel = New System.Windows.Forms.Label()
            Me.Pay_Time_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.AccountantBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.paymentBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            CType(Me.DataGridView3, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.BillBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.DataGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.PatientBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.AccountantBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.panel3.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.paymentBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(10, 0, 10, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(1067, 25)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'paymentBindingSource
            '
            Me.paymentBindingSource.DataMember = "payment"
            Me.paymentBindingSource.DataSource = Me.newDataSet
            '
            'newDataSet
            '
            Me.newDataSet.DataSetName = "NewDataSet"
            Me.newDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(35, 22)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(50, 23)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 25)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(23, 22)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(23, 22)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.BackgroundImage = Global.MySqlWindowsFormsApplication5.My.Resources.Resources._6800415_light_blue_backgrounds
            Me.Panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
            Me.Panel1.Controls.Add(Me.DataGridView3)
            Me.Panel1.Controls.Add(Me.DataGridView1)
            Me.Panel1.Controls.Add(Me.Button7)
            Me.Panel1.Controls.Add(Me.Label1)
            Me.Panel1.Controls.Add(Me.Button6)
            Me.Panel1.Controls.Add(Me.Cmdmain)
            Me.Panel1.Controls.Add(Me.Button5)
            Me.Panel1.Controls.Add(Me.Button4)
            Me.Panel1.Controls.Add(Me.Cmdend)
            Me.Panel1.Controls.Add(Me.Button3)
            Me.Panel1.Controls.Add(Me.CmdHelp)
            Me.Panel1.Controls.Add(Me.Button2)
            Me.Panel1.Controls.Add(Me.Pay_IDLabel)
            Me.Panel1.Controls.Add(Me.Button1)
            Me.Panel1.Controls.Add(Me.Pay_IDTextBox)
            Me.Panel1.Controls.Add(Me.Accnt_IDLabel)
            Me.Panel1.Controls.Add(Me.Accnt_ID_comboBox)
            Me.Panel1.Controls.Add(Me.Bill_IDLabel)
            Me.Panel1.Controls.Add(Me.Bill_ID_comboBox)
            Me.Panel1.Controls.Add(Me.Patient_IDLabel)
            Me.Panel1.Controls.Add(Me.Patient_ID_comboBox)
            Me.Panel1.Controls.Add(Me.Pay_DateLabel)
            Me.Panel1.Controls.Add(Me.Pay_Date_dateTimePicker)
            Me.Panel1.Controls.Add(Me.Pay_TimeLabel)
            Me.Panel1.Controls.Add(Me.Pay_Time_dateTimePicker)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.Location = New System.Drawing.Point(10, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(10, 3, 10, 3)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(1047, 635)
            Me.Panel1.TabIndex = 1
            '
            'DataGridView3
            '
            Me.DataGridView3.AllowUserToAddRows = False
            Me.DataGridView3.AllowUserToDeleteRows = False
            Me.DataGridView3.AllowUserToOrderColumns = True
            Me.DataGridView3.AutoGenerateColumns = False
            Me.DataGridView3.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Me.DataGridView3.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.BillIDDataGridViewTextBoxColumn, Me.BillPurposeDataGridViewTextBoxColumn, Me.BillTotalDataGridViewTextBoxColumn})
            Me.DataGridView3.DataSource = Me.BillBindingSource
            Me.DataGridView3.Location = New System.Drawing.Point(227, 363)
            Me.DataGridView3.Name = "DataGridView3"
            Me.DataGridView3.ReadOnly = True
            Me.DataGridView3.Size = New System.Drawing.Size(698, 157)
            Me.DataGridView3.TabIndex = 100
            '
            'BillIDDataGridViewTextBoxColumn
            '
            Me.BillIDDataGridViewTextBoxColumn.DataPropertyName = "Bill_ID"
            Me.BillIDDataGridViewTextBoxColumn.HeaderText = "Bill_ID"
            Me.BillIDDataGridViewTextBoxColumn.Name = "BillIDDataGridViewTextBoxColumn"
            Me.BillIDDataGridViewTextBoxColumn.ReadOnly = True
            '
            'BillPurposeDataGridViewTextBoxColumn
            '
            Me.BillPurposeDataGridViewTextBoxColumn.DataPropertyName = "Bill_Purpose"
            Me.BillPurposeDataGridViewTextBoxColumn.HeaderText = "Bill_Purpose"
            Me.BillPurposeDataGridViewTextBoxColumn.Name = "BillPurposeDataGridViewTextBoxColumn"
            Me.BillPurposeDataGridViewTextBoxColumn.ReadOnly = True
            '
            'BillTotalDataGridViewTextBoxColumn
            '
            Me.BillTotalDataGridViewTextBoxColumn.DataPropertyName = "Bill_Total"
            Me.BillTotalDataGridViewTextBoxColumn.HeaderText = "Bill_Total"
            Me.BillTotalDataGridViewTextBoxColumn.Name = "BillTotalDataGridViewTextBoxColumn"
            Me.BillTotalDataGridViewTextBoxColumn.ReadOnly = True
            '
            'BillBindingSource
            '
            Me.BillBindingSource.DataMember = "bill"
            Me.BillBindingSource.DataSource = Me.newDataSet
            '
            'DataGridView1
            '
            Me.DataGridView1.AllowUserToAddRows = False
            Me.DataGridView1.AllowUserToDeleteRows = False
            Me.DataGridView1.AllowUserToOrderColumns = True
            Me.DataGridView1.AutoGenerateColumns = False
            Me.DataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Me.DataGridView1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.PatientIDDataGridViewTextBoxColumn, Me.PatientNameDataGridViewTextBoxColumn, Me.AgeDataGridViewTextBoxColumn, Me.GenderDataGridViewTextBoxColumn, Me.AddressDataGridViewTextBoxColumn, Me.DOBDataGridViewTextBoxColumn, Me.MobnumDataGridViewTextBoxColumn, Me.DichargedDataGridViewTextBoxColumn})
            Me.DataGridView1.DataSource = Me.PatientBindingSource
            Me.DataGridView1.Location = New System.Drawing.Point(216, 264)
            Me.DataGridView1.Name = "DataGridView1"
            Me.DataGridView1.ReadOnly = True
            Me.DataGridView1.Size = New System.Drawing.Size(709, 93)
            Me.DataGridView1.TabIndex = 98
            '
            'PatientIDDataGridViewTextBoxColumn
            '
            Me.PatientIDDataGridViewTextBoxColumn.DataPropertyName = "Patient_ID"
            Me.PatientIDDataGridViewTextBoxColumn.HeaderText = "Patient_ID"
            Me.PatientIDDataGridViewTextBoxColumn.Name = "PatientIDDataGridViewTextBoxColumn"
            Me.PatientIDDataGridViewTextBoxColumn.ReadOnly = True
            '
            'PatientNameDataGridViewTextBoxColumn
            '
            Me.PatientNameDataGridViewTextBoxColumn.DataPropertyName = "Patient_Name"
            Me.PatientNameDataGridViewTextBoxColumn.HeaderText = "Patient_Name"
            Me.PatientNameDataGridViewTextBoxColumn.Name = "PatientNameDataGridViewTextBoxColumn"
            Me.PatientNameDataGridViewTextBoxColumn.ReadOnly = True
            '
            'AgeDataGridViewTextBoxColumn
            '
            Me.AgeDataGridViewTextBoxColumn.DataPropertyName = "Age"
            Me.AgeDataGridViewTextBoxColumn.HeaderText = "Age"
            Me.AgeDataGridViewTextBoxColumn.Name = "AgeDataGridViewTextBoxColumn"
            Me.AgeDataGridViewTextBoxColumn.ReadOnly = True
            '
            'GenderDataGridViewTextBoxColumn
            '
            Me.GenderDataGridViewTextBoxColumn.DataPropertyName = "Gender"
            Me.GenderDataGridViewTextBoxColumn.HeaderText = "Gender"
            Me.GenderDataGridViewTextBoxColumn.Name = "GenderDataGridViewTextBoxColumn"
            Me.GenderDataGridViewTextBoxColumn.ReadOnly = True
            '
            'AddressDataGridViewTextBoxColumn
            '
            Me.AddressDataGridViewTextBoxColumn.DataPropertyName = "Address"
            Me.AddressDataGridViewTextBoxColumn.HeaderText = "Address"
            Me.AddressDataGridViewTextBoxColumn.Name = "AddressDataGridViewTextBoxColumn"
            Me.AddressDataGridViewTextBoxColumn.ReadOnly = True
            '
            'DOBDataGridViewTextBoxColumn
            '
            Me.DOBDataGridViewTextBoxColumn.DataPropertyName = "D-O-B"
            Me.DOBDataGridViewTextBoxColumn.HeaderText = "D-O-B"
            Me.DOBDataGridViewTextBoxColumn.Name = "DOBDataGridViewTextBoxColumn"
            Me.DOBDataGridViewTextBoxColumn.ReadOnly = True
            '
            'MobnumDataGridViewTextBoxColumn
            '
            Me.MobnumDataGridViewTextBoxColumn.DataPropertyName = "Mob_num"
            Me.MobnumDataGridViewTextBoxColumn.HeaderText = "Mob_num"
            Me.MobnumDataGridViewTextBoxColumn.Name = "MobnumDataGridViewTextBoxColumn"
            Me.MobnumDataGridViewTextBoxColumn.ReadOnly = True
            '
            'DichargedDataGridViewTextBoxColumn
            '
            Me.DichargedDataGridViewTextBoxColumn.DataPropertyName = "Dicharged"
            Me.DichargedDataGridViewTextBoxColumn.HeaderText = "Dicharged"
            Me.DichargedDataGridViewTextBoxColumn.Name = "DichargedDataGridViewTextBoxColumn"
            Me.DichargedDataGridViewTextBoxColumn.ReadOnly = True
            '
            'PatientBindingSource
            '
            Me.PatientBindingSource.DataMember = "patient"
            Me.PatientBindingSource.DataSource = Me.newDataSet
            '
            'Button7
            '
            Me.Button7.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button7.FlatAppearance.BorderSize = 4
            Me.Button7.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button7.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button7.Location = New System.Drawing.Point(761, 538)
            Me.Button7.Name = "Button7"
            Me.Button7.Size = New System.Drawing.Size(61, 40)
            Me.Button7.TabIndex = 92
            Me.Button7.Text = "Delete"
            Me.Button7.UseVisualStyleBackColor = True
            '
            'Label1
            '
            Me.Label1.AutoSize = True
            Me.Label1.BackColor = System.Drawing.Color.Transparent
            Me.Label1.Font = New System.Drawing.Font("Modern No. 20", 30.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Label1.Location = New System.Drawing.Point(398, 3)
            Me.Label1.Name = "Label1"
            Me.Label1.Size = New System.Drawing.Size(388, 41)
            Me.Label1.TabIndex = 51
            Me.Label1.Text = "Payment Information"
            '
            'Button6
            '
            Me.Button6.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button6.FlatAppearance.BorderSize = 4
            Me.Button6.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button6.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button6.Location = New System.Drawing.Point(359, 538)
            Me.Button6.Name = "Button6"
            Me.Button6.Size = New System.Drawing.Size(61, 40)
            Me.Button6.TabIndex = 91
            Me.Button6.Text = "Addnew"
            Me.Button6.UseVisualStyleBackColor = True
            '
            'Cmdmain
            '
            Me.Cmdmain.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Cmdmain.FlatAppearance.BorderSize = 4
            Me.Cmdmain.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Cmdmain.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Cmdmain.Location = New System.Drawing.Point(538, 590)
            Me.Cmdmain.Name = "Cmdmain"
            Me.Cmdmain.Size = New System.Drawing.Size(88, 33)
            Me.Cmdmain.TabIndex = 50
            Me.Cmdmain.Text = "Return to Main"
            Me.Cmdmain.UseVisualStyleBackColor = True
            '
            'Button5
            '
            Me.Button5.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button5.FlatAppearance.BorderSize = 4
            Me.Button5.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button5.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button5.Location = New System.Drawing.Point(694, 538)
            Me.Button5.Name = "Button5"
            Me.Button5.Size = New System.Drawing.Size(61, 40)
            Me.Button5.TabIndex = 90
            Me.Button5.Text = "Save"
            Me.Button5.UseVisualStyleBackColor = True
            '
            'Button4
            '
            Me.Button4.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button4.FlatAppearance.BorderSize = 4
            Me.Button4.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button4.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button4.Location = New System.Drawing.Point(627, 538)
            Me.Button4.Name = "Button4"
            Me.Button4.Size = New System.Drawing.Size(61, 40)
            Me.Button4.TabIndex = 89
            Me.Button4.Text = "Last"
            Me.Button4.UseVisualStyleBackColor = True
            '
            'Cmdend
            '
            Me.Cmdend.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Cmdend.FlatAppearance.BorderSize = 4
            Me.Cmdend.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Cmdend.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Cmdend.Location = New System.Drawing.Point(632, 590)
            Me.Cmdend.Name = "Cmdend"
            Me.Cmdend.Size = New System.Drawing.Size(61, 33)
            Me.Cmdend.TabIndex = 49
            Me.Cmdend.Text = "Exit"
            Me.Cmdend.UseVisualStyleBackColor = True
            '
            'Button3
            '
            Me.Button3.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button3.FlatAppearance.BorderSize = 4
            Me.Button3.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button3.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button3.Location = New System.Drawing.Point(426, 538)
            Me.Button3.Name = "Button3"
            Me.Button3.Size = New System.Drawing.Size(61, 40)
            Me.Button3.TabIndex = 88
            Me.Button3.Text = "First"
            Me.Button3.UseVisualStyleBackColor = True
            '
            'CmdHelp
            '
            Me.CmdHelp.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.CmdHelp.FlatAppearance.BorderSize = 4
            Me.CmdHelp.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.CmdHelp.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.CmdHelp.Location = New System.Drawing.Point(495, 590)
            Me.CmdHelp.Name = "CmdHelp"
            Me.CmdHelp.Size = New System.Drawing.Size(37, 33)
            Me.CmdHelp.TabIndex = 48
            Me.CmdHelp.Text = "Help"
            Me.CmdHelp.UseVisualStyleBackColor = True
            '
            'Button2
            '
            Me.Button2.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button2.FlatAppearance.BorderSize = 4
            Me.Button2.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button2.Location = New System.Drawing.Point(493, 538)
            Me.Button2.Name = "Button2"
            Me.Button2.Size = New System.Drawing.Size(61, 40)
            Me.Button2.TabIndex = 87
            Me.Button2.Text = "Previous"
            Me.Button2.UseVisualStyleBackColor = True
            '
            'Pay_IDLabel
            '
            Me.Pay_IDLabel.AutoSize = True
            Me.Pay_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Pay_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Pay_IDLabel.Location = New System.Drawing.Point(446, 83)
            Me.Pay_IDLabel.Name = "Pay_IDLabel"
            Me.Pay_IDLabel.Size = New System.Drawing.Size(61, 20)
            Me.Pay_IDLabel.TabIndex = 1
            Me.Pay_IDLabel.Text = "Pay_ID"
            '
            'Button1
            '
            Me.Button1.FlatAppearance.BorderColor = System.Drawing.Color.Black
            Me.Button1.FlatAppearance.BorderSize = 4
            Me.Button1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Teal
            Me.Button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.Button1.Location = New System.Drawing.Point(560, 538)
            Me.Button1.Name = "Button1"
            Me.Button1.Size = New System.Drawing.Size(61, 40)
            Me.Button1.TabIndex = 86
            Me.Button1.Text = "Next"
            Me.Button1.UseVisualStyleBackColor = True
            '
            'Pay_IDTextBox
            '
            Me.Pay_IDTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.paymentBindingSource, "Pay_ID", True))
            Me.Pay_IDTextBox.Location = New System.Drawing.Point(513, 83)
            Me.Pay_IDTextBox.Name = "Pay_IDTextBox"
            Me.Pay_IDTextBox.Size = New System.Drawing.Size(206, 20)
            Me.Pay_IDTextBox.TabIndex = 2
            '
            'Accnt_IDLabel
            '
            Me.Accnt_IDLabel.AutoSize = True
            Me.Accnt_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Accnt_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Accnt_IDLabel.Location = New System.Drawing.Point(431, 110)
            Me.Accnt_IDLabel.Name = "Accnt_IDLabel"
            Me.Accnt_IDLabel.Size = New System.Drawing.Size(76, 20)
            Me.Accnt_IDLabel.TabIndex = 3
            Me.Accnt_IDLabel.Text = "Accnt_ID"
            '
            'Accnt_ID_comboBox
            '
            Me.Accnt_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Accnt_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Accnt_ID_comboBox.FormattingEnabled = True
            Me.Accnt_ID_comboBox.Location = New System.Drawing.Point(513, 109)
            Me.Accnt_ID_comboBox.Name = "Accnt_ID_comboBox"
            Me.Accnt_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Accnt_ID_comboBox.TabIndex = 4
            '
            'Bill_IDLabel
            '
            Me.Bill_IDLabel.AutoSize = True
            Me.Bill_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Bill_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Bill_IDLabel.Location = New System.Drawing.Point(448, 136)
            Me.Bill_IDLabel.Name = "Bill_IDLabel"
            Me.Bill_IDLabel.Size = New System.Drawing.Size(55, 20)
            Me.Bill_IDLabel.TabIndex = 5
            Me.Bill_IDLabel.Text = "Bill_ID"
            '
            'Bill_ID_comboBox
            '
            Me.Bill_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Bill_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Bill_ID_comboBox.FormattingEnabled = True
            Me.Bill_ID_comboBox.Location = New System.Drawing.Point(513, 135)
            Me.Bill_ID_comboBox.Name = "Bill_ID_comboBox"
            Me.Bill_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Bill_ID_comboBox.TabIndex = 6
            '
            'Patient_IDLabel
            '
            Me.Patient_IDLabel.AutoSize = True
            Me.Patient_IDLabel.BackColor = System.Drawing.Color.Transparent
            Me.Patient_IDLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Patient_IDLabel.Location = New System.Drawing.Point(422, 162)
            Me.Patient_IDLabel.Name = "Patient_IDLabel"
            Me.Patient_IDLabel.Size = New System.Drawing.Size(85, 20)
            Me.Patient_IDLabel.TabIndex = 7
            Me.Patient_IDLabel.Text = "Patient_ID"
            '
            'Patient_ID_comboBox
            '
            Me.Patient_ID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.Patient_ID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.Patient_ID_comboBox.FormattingEnabled = True
            Me.Patient_ID_comboBox.Location = New System.Drawing.Point(513, 162)
            Me.Patient_ID_comboBox.Name = "Patient_ID_comboBox"
            Me.Patient_ID_comboBox.Size = New System.Drawing.Size(206, 21)
            Me.Patient_ID_comboBox.TabIndex = 8
            '
            'Pay_DateLabel
            '
            Me.Pay_DateLabel.AutoSize = True
            Me.Pay_DateLabel.BackColor = System.Drawing.Color.Transparent
            Me.Pay_DateLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Pay_DateLabel.Location = New System.Drawing.Point(428, 189)
            Me.Pay_DateLabel.Name = "Pay_DateLabel"
            Me.Pay_DateLabel.Size = New System.Drawing.Size(79, 20)
            Me.Pay_DateLabel.TabIndex = 9
            Me.Pay_DateLabel.Text = "Pay_Date"
            '
            'Pay_Date_dateTimePicker
            '
            Me.Pay_Date_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.Pay_Date_dateTimePicker.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.paymentBindingSource, "Pay_Date", True))
            Me.Pay_Date_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.Pay_Date_dateTimePicker.Location = New System.Drawing.Point(513, 188)
            Me.Pay_Date_dateTimePicker.Name = "Pay_Date_dateTimePicker"
            Me.Pay_Date_dateTimePicker.Size = New System.Drawing.Size(206, 20)
            Me.Pay_Date_dateTimePicker.TabIndex = 10
            Me.Pay_Date_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'Pay_TimeLabel
            '
            Me.Pay_TimeLabel.AutoSize = True
            Me.Pay_TimeLabel.BackColor = System.Drawing.Color.Transparent
            Me.Pay_TimeLabel.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Pay_TimeLabel.Location = New System.Drawing.Point(429, 215)
            Me.Pay_TimeLabel.Name = "Pay_TimeLabel"
            Me.Pay_TimeLabel.Size = New System.Drawing.Size(78, 20)
            Me.Pay_TimeLabel.TabIndex = 11
            Me.Pay_TimeLabel.Text = "Pay_Time"
            '
            'Pay_Time_dateTimePicker
            '
            Me.Pay_Time_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"
            Me.Pay_Time_dateTimePicker.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.paymentBindingSource, "Pay_Time", True))
            Me.Pay_Time_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.Pay_Time_dateTimePicker.Location = New System.Drawing.Point(513, 214)
            Me.Pay_Time_dateTimePicker.Name = "Pay_Time_dateTimePicker"
            Me.Pay_Time_dateTimePicker.Size = New System.Drawing.Size(206, 20)
            Me.Pay_Time_dateTimePicker.TabIndex = 12
            Me.Pay_Time_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'AccountantBindingSource
            '
            Me.AccountantBindingSource.DataMember = "accountant"
            Me.AccountantBindingSource.DataSource = Me.newDataSet
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 25)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(1067, 645)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(1057, 0)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(10, 635)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(10, 635)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 635)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(1067, 10)
            Me.panel6.TabIndex = 6
            '
            'frmpaymentacc
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(1067, 670)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.Name = "frmpaymentacc"
            Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
            Me.Text = "Payment"
            Me.WindowState = System.Windows.Forms.FormWindowState.Maximized
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.paymentBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            CType(Me.DataGridView3, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.BillBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.DataGridView1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.PatientBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.AccountantBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
        Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
        Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
        Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
        Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
        Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
        Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
        Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
        Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
        Friend WithEvents Panel1 As System.Windows.Forms.Panel
        Friend WithEvents newDataSet As NewDataSet
        Friend WithEvents paymentBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents Pay_IDTextBox As System.Windows.Forms.TextBox
        Friend WithEvents Pay_IDLabel As System.Windows.Forms.Label
        Friend WithEvents Accnt_ID_comboBox As System.Windows.Forms.ComboBox
        Friend WithEvents Accnt_IDLabel As System.Windows.Forms.Label
        Friend WithEvents Bill_ID_comboBox As System.Windows.Forms.ComboBox
        Friend WithEvents Bill_IDLabel As System.Windows.Forms.Label
        Friend WithEvents Patient_ID_comboBox As System.Windows.Forms.ComboBox
        Friend WithEvents Patient_IDLabel As System.Windows.Forms.Label
        Friend WithEvents Pay_Date_dateTimePicker As System.Windows.Forms.DateTimePicker
        Friend WithEvents Pay_DateLabel As System.Windows.Forms.Label
        Friend WithEvents Pay_Time_dateTimePicker As System.Windows.Forms.DateTimePicker
        Friend WithEvents Pay_TimeLabel As System.Windows.Forms.Label
        Friend WithEvents panel3 As System.Windows.Forms.Panel
        Friend WithEvents panel4 As System.Windows.Forms.Panel
        Friend WithEvents panel5 As System.Windows.Forms.Panel
        Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents Cmdmain As System.Windows.Forms.Button
        Friend WithEvents Cmdend As System.Windows.Forms.Button
        Friend WithEvents CmdHelp As System.Windows.Forms.Button
        Friend WithEvents Label1 As System.Windows.Forms.Label
        Friend WithEvents Button7 As System.Windows.Forms.Button
        Friend WithEvents Button6 As System.Windows.Forms.Button
        Friend WithEvents Button5 As System.Windows.Forms.Button
        Friend WithEvents Button4 As System.Windows.Forms.Button
        Friend WithEvents Button3 As System.Windows.Forms.Button
        Friend WithEvents Button2 As System.Windows.Forms.Button
        Friend WithEvents Button1 As System.Windows.Forms.Button
        Friend WithEvents DataGridView3 As System.Windows.Forms.DataGridView
        Friend WithEvents BillIDDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents BillPurposeDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents BillTotalDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents BillBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents AccountantBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents DataGridView1 As System.Windows.Forms.DataGridView
        Friend WithEvents PatientIDDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents PatientNameDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents AgeDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents GenderDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents AddressDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents DOBDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents MobnumDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents DichargedDataGridViewTextBoxColumn As System.Windows.Forms.DataGridViewTextBoxColumn
        Friend WithEvents PatientBindingSource As System.Windows.Forms.BindingSource

    End Class
	
End Namespace
