' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace MySqlWindowsFormsApplication5
	
	Public Class frmreceptionist
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmreceptionist_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=localhost;user id=root;database=hospital;password=fus939597;persistsecurityinfo=True;allowuservariables=True;"
			ad = New MySqlDataAdapter("select * from `receptionist`", strConn)
			Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
			ad.Fill(Me.newDataSet.receptionist)
			ad.DeleteCommand = builder.GetDeleteCommand()
			ad.UpdateCommand = builder.GetUpdateCommand()
			ad.InsertCommand = builder.GetInsertCommand()
			Dim ad3 As MySqlDataAdapter
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			receptionistBindingSource.EndEdit()
			ad.Update(Me.newDataSet.receptionist)
		End Sub
		
		Private Sub frmreceptionist_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
        Private Sub Rep_IDTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Rep_IDTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Rep_IDTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Rep_IDTextBox, "The field Rep_ID is required")
            End If
            Dim v As Integer
            Dim s As String = Rep_IDTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(Rep_IDTextBox, "The field Rep_ID must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Rep_IDTextBox, "")
            End If
        End Sub
		
        Private Sub Rep_NameTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Rep_NameTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Rep_NameTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Rep_NameTextBox, "The field Rep_Name is required")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Rep_NameTextBox, "")
            End If
        End Sub
		
        Private Sub AgeTextBox_Validating(sender As Object, e As CancelEventArgs) Handles AgeTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(AgeTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(AgeTextBox, "The field Age is required")
            End If
            Dim v As Integer
            Dim s As String = AgeTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(AgeTextBox, "The field Age must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(AgeTextBox, "")
            End If
        End Sub
		
        Private Sub AddressTextBox_Validating(sender As Object, e As CancelEventArgs) Handles AddressTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(AddressTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(AddressTextBox, "The field Address is required")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(AddressTextBox, "")
            End If
        End Sub
		
        Private Sub Mob_NumTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Mob_NumTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Mob_NumTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Mob_NumTextBox, "The field Mob_Num is required")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Mob_NumTextBox, "")
            End If
        End Sub
		
        Private Sub ShiftTextBox_Validating(sender As Object, e As CancelEventArgs) Handles ShiftTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(ShiftTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(ShiftTextBox, "The field Shift is required")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(ShiftTextBox, "")
            End If
        End Sub
		
		
        Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
            receptionistBindingSource.AddNew()
        End Sub
        Private Sub Cmdmain_Click(sender As Object, e As EventArgs) Handles Cmdmain.Click
            frmmainreceptionist.Show()
            Me.Hide()
        End Sub
        Private Sub Cmdend_Click(sender As Object, e As EventArgs) Handles Cmdend.Click
            Dim response As String
            response = MsgBox("Do you want to close?", MsgBoxStyle.YesNoCancel) 'a message will be displayed and answer will be stored as string variable
            If response = vbYes Then 'use of selection programming structure
                Me.Close()
            End If
        End Sub
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            receptionistBindingSource.MoveNext()
        End Sub

        Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
            receptionistBindingSource.MovePrevious()
        End Sub

        Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
            receptionistBindingSource.MoveFirst()
        End Sub

        Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
            receptionistBindingSource.MoveLast()
        End Sub

        Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
            ad.Update(Me.newDataSet.receptionist)
        End Sub

        Private Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
            receptionistBindingSource.AddNew()
        End Sub

        Private Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
            receptionistBindingSource.RemoveCurrent()
        End Sub
	End Class
	
End Namespace
