' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace MySqlWindowsFormsApplication5
	
	Public Class frmroom
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmroom_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=localhost;user id=root;database=hospital;password=fus939597;persistsecurityinfo=True;allowuservariables=True;"
			ad = New MySqlDataAdapter("select * from `room`", strConn)
			Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
			ad.Fill(Me.newDataSet.room)
			ad.DeleteCommand = builder.GetDeleteCommand()
			ad.UpdateCommand = builder.GetUpdateCommand()
			ad.InsertCommand = builder.GetInsertCommand()
			Dim ad3 As MySqlDataAdapter
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			roomBindingSource.EndEdit()
			ad.Update(Me.newDataSet.room)
		End Sub
		
		Private Sub frmroom_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
        Private Sub Room_IDTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Room_IDTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Room_IDTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_IDTextBox, "The field Room_ID is required")
            End If
            Dim v As Integer
            Dim s As String = Room_IDTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_IDTextBox, "The field Room_ID must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Room_IDTextBox, "")
            End If
        End Sub
		
        Private Sub Room_numTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Room_numTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Room_numTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_numTextBox, "The field Room_num is required")
            End If
            Dim v As Integer
            Dim s As String = Room_numTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_numTextBox, "The field Room_num must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Room_numTextBox, "")
            End If
        End Sub
		
        Private Sub Room_TypeTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Room_TypeTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Room_TypeTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_TypeTextBox, "The field Room_Type is required")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Room_TypeTextBox, "")
            End If
        End Sub
		
        Private Sub Room_CostTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Room_CostTextBox.Validating

            e.Cancel = False
            If String.IsNullOrEmpty(Room_CostTextBox.Text) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_CostTextBox, "The field Room_Cost is required")
            End If
            Dim v As Integer
            Dim s As String = Room_CostTextBox.Text
            If Not Integer.TryParse(s, v) Then
                e.Cancel = True
                ErrorProvider1.SetError(Room_CostTextBox, "The field Room_Cost must be Integer.")
            End If
            If Not e.Cancel Then
                ErrorProvider1.SetError(Room_CostTextBox, "")
            End If
        End Sub
		
		
        Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
            roomBindingSource.AddNew()
        End Sub
        Private Sub Cmdmain_Click(sender As Object, e As EventArgs) Handles Cmdmain.Click
            frmmainreceptionist.Show()
            Me.Hide()
        End Sub
        Private Sub Cmdend_Click(sender As Object, e As EventArgs) Handles Cmdend.Click
            Dim response As String
            response = MsgBox("Do you want to close?", MsgBoxStyle.YesNoCancel) 'a message will be displayed and answer will be stored as string variable
            If response = vbYes Then 'use of selection programming structure
                Me.Close()
            End If
        End Sub
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            roomBindingSource.MoveNext()
        End Sub

        Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
            roomBindingSource.MovePrevious()
        End Sub

        Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
            roomBindingSource.MoveFirst()
        End Sub

        Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
            roomBindingSource.MoveLast()
        End Sub

        Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
            ad.Update(Me.newDataSet.room)
        End Sub

        Private Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
            roomBindingSource.AddNew()
        End Sub

        Private Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
            roomBindingSource.RemoveCurrent()
        End Sub
	End Class
	
End Namespace
